#!/usr/bin/env bash

echo "NJIT NCAE 2025 Scoring SSH Setup Script"
echo

# Check for root.
if [ "$EUID" -ne 0 ]
  then echo "This script must be ran as root."
  exit 1
fi

groupadd pointers
ln -s /bin/bash /usr/local/bin/rbash

function createUser {
  if id "$1" >/dev/null 2>&1; then
    usermod -a -G pointers "$1"
    usermod -s /usr/local/bin/rbash "$1"
  else
    useradd -G pointers -s /usr/local/bin/rbash "$1"
  fi
}

# Repeat for scoring users.
createUser SCORING_USER

cat <<EOF >>/etc/ssh/sshd_config
Match Group pointers
    AuthorizedKeysFile /etc/pointers.pub
EOF

# Add SSH key
echo "SCORING SSH KEY" > /etc/pointers.pub

echo "Restarting SSH daemon."
systemctl restart sshd.service
